"""
Configuration: two required environment variables, nothing else.

Rewritten from market_data/config.py (the source system), which resolves a
settings.yml file through four fallback locations and returns WAL tuning and
memory-limit knobs alongside the database path -- all irrelevant to a
single-symbol historical collector with no live daemon. This module keeps
exactly one behaviour from the source, because it is the behaviour that
prevents a specific, previously-real failure:

`resolve_db_path()` returns None rather than guessing a default when
SPOT_DB_PATH is unset. The source's equivalent function used to fall back to
a path under $HOME that SQLite happily CREATES on open -- so an unconfigured
run would proceed, open a brand-new empty database, and report "0 bars"
looking exactly like success. It happened twice on the source system before
the fallback was removed. This module never had that fallback: callers that
get None back are expected to refuse to run (src/cli.py does), not invent a
path.

Also home to `load_dotenv()`, which `src/cli.py::main()` and `verify.sh`
both call before reading anything else -- see that function's docstring for
the precedence rule. Added after independent testing identified the old
"`cp .env.example .env`, then remember to also `set -a; source .env; set +a`
yourself" two-step as the most likely point a first-time, non-developer user
gave up.
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Optional, Union


def load_dotenv(env_path: Union[str, Path, None] = None) -> None:
    """Load KEY=VALUE lines from a .env file into os.environ.

    Fills in only variables not already meaningfully set in the real
    environment -- a variable exported in a shell profile, set by
    docker-compose.yml's env_file:, or otherwise already present always
    wins over this file. That precedence is the point: this exists to
    remove the "you must `set -a; source .env; set +a` yourself" step from
    a native install, not to change what wins when a variable is set in
    both places.

    "Meaningfully set" deliberately excludes an exported-but-empty variable
    (`export SPOT_DB_PATH=`, or the same left blank in a launched shell) --
    plain `os.environ.setdefault()` treats that as already set and would
    let it silently mask a real value sitting in .env, which is exactly the
    kind of "I changed it and nothing happened" trap this module exists to
    avoid (see resolve_db_path()'s docstring). An empty string in the real
    environment is treated the same as absent, for this function's purposes
    only -- it does not touch os.environ.pop() or otherwise alter the
    variable if .env has nothing for it either.

    Defaults to the repository root's `.env` (this file lives at
    `src/config.py`, so the repo root is two levels up). A missing file is
    not an error -- every variable this repo reads has always been allowed
    to arrive some other way, and callers that need one still get a clear
    error from resolve_db_path()/resolve_upstox_token() (or, for the three
    Upstox app-registration variables, from src/upstox/session.py) when
    it's genuinely absent everywhere.
    """
    path = Path(env_path) if env_path else Path(__file__).resolve().parent.parent / ".env"
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        if key and not os.environ.get(key):
            os.environ[key] = value


def resolve_db_path(explicit: Optional[str] = None) -> Optional[str]:
    """Path to the SQLite database, or None if nothing named one.

    Priority: explicit argument, then SPOT_DB_PATH. No default path --
    returning None is what lets a caller distinguish "configured" from
    "about to silently create an empty database".
    """
    raw = explicit or os.environ.get("SPOT_DB_PATH")
    return os.path.expanduser(raw) if raw else None


def resolve_upstox_token(explicit: Optional[str] = None) -> Optional[str]:
    """The daily Upstox access token, or None if unset.

    This token expires every morning and is generated by hand from the
    Upstox developer dashboard (see docs/CREDENTIALS.md) -- there is no
    refresh flow here, and none should be added. A stale token fails at the
    Upstox API with an auth error; it is not something this module can
    detect in advance.
    """
    raw = explicit or os.environ.get("UPSTOX_ACCESS_TOKEN")
    return raw.strip() if raw else None
